// Code generated by hertz generator.

package main

import (
	handler "github.com/cloudwego/goapi/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// 登录登出改密换绑
	r.POST("/login", handler.Login)
	r.POST("/logout", handler.Logout)
	r.POST("/change_password", handler.ChangePwd)
	r.POST("/change_email", handler.ChangeEmail)

	// 自动打卡注册
	r.POST("/ahr_register", handler.AhrRegister)
}
