// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, utils.H{
		"message": "pong",
	})
}
func Login(ctx context.Context, c *app.RequestContext) {

}
func Logout(ctx context.Context, c *app.RequestContext) {

}
func ChangePwd(ctx context.Context, c *app.RequestContext) {

}
func ChangeEmail(ctx context.Context, c *app.RequestContext) {

}
func AhrRegister(ctx context.Context, c *app.RequestContext) {

}
func SendVerifyCode(ctx context.Context, c *app.RequestContext) {

}
