// Code generated by hertz generator.

package handler

import (
	"context"
	"strconv"
	"time"

	"github.com/cloudwego/goapi/biz/dal"
	"github.com/cloudwego/goapi/biz/mail"
	util "github.com/cloudwego/goapi/biz/utils"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	c.JSON(200, utils.H{
		"message": "pong",
	})
}
func Login(ctx context.Context, c *app.RequestContext) {
	IP := c.RemoteAddr().String()
	IP = util.DeletePort(IP)
	email := c.PostForm("email")
	pwd := c.PostForm("pwd")
	var uname, sessionId string
	var error_code int
	error_code = SUCCESS
	uname, sessionId, error_code = doRealLogin(ctx, email, pwd, IP)
	if sessionId != "" {
		c.SetCookie("session_id", sessionId, 24*60*60, "/", "z-coding.cn", protocol.CookieSameSiteLaxMode, false, false)
	}
	c.JSON(200, utils.H{
		"uname":      uname,
		"error_code": error_code,
	})
}
func Logout(ctx context.Context, c *app.RequestContext) {

}
func UserRegister(ctx context.Context, c *app.RequestContext) {
	token := c.PostForm("token")
	verify_code := c.PostForm("verify_code")
	uname := c.PostForm("uname")
	pwd := c.PostForm("pwd")
	error_code := SUCCESS
	if token == "" || verify_code == "" || uname == "" || pwd == "" {
		error_code = BAD_PARAM
	} else if !dal.CheckVerifyCode(ctx, token, verify_code) {
		error_code = VERIFY_ERROR
	} else if !dal.AddNewUser(ctx, token, verify_code, uname, pwd) {
		error_code = SERVER_ERROR
	}
	c.JSON(200, utils.H{
		"error_code": error_code,
	})
}
func ChangePwd(ctx context.Context, c *app.RequestContext) {

}
func ChangeEmail(ctx context.Context, c *app.RequestContext) {

}
func AhrRegister(ctx context.Context, c *app.RequestContext) {

}
func EmailVerify(ctx context.Context, c *app.RequestContext) {
	email := c.PostForm("email")
	error_code := SUCCESS
	token := ""
	var err error
	defer func() {
		c.JSON(200, utils.H{
			"token":      token,
			"error_code": error_code,
		})
	}()
	if email == "" {
		error_code = BAD_PARAM
		return
	}
	token, err = mail.SendVerifyCode(ctx, email)
	if err != nil {
		token = ""
		error_code = EMAIL_SEND_ERROR
		return
	}
	return
}
func SessionVerify(ctx context.Context, c *app.RequestContext) {

}

func doRealLogin(ctx context.Context, email, pwd, IP string) (string, string, int) {
	if email == "" || pwd == "" {
		return "", "", BAD_PARAM
	}
	if pwd != dal.QueryUserPwd(email) {
		return "", "", PWD_ERROR
	}
	uname, uid := dal.QueryUserInfo(email)
	sessionId, error_code := makeSessionId(ctx, uid, IP)
	return uname, sessionId, error_code
}

func makeSessionId(ctx context.Context, uid int64, IP string) (string, int) {
	sessionId := util.RandomStringCreate()
	value := sessionId + IP
	key := "[sessionId]" + strconv.FormatInt(uid, 10)
	err := dal.RedisAdd(ctx, key, value, time.Hour*12)
	if err != nil {
		return "", REDIS_ERROR
	}
	return sessionId, SUCCESS
}
